version: '3.3'
services:
  db:
    image: postgres
    container_name: logDB
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - db.env
    environment:
      - TZ=America/New_York
    networks:
      - backend
    volumes:
      - logStorage:/var/lib/postgresql/data
  app:
    container_name: logServer
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - app.env
    environment:
      - TZ=America/New_York
    ports:
      - "8080:8080"
    command: go run main.go
volumes:
  logStorage:
networks:
  backend:
    driver: "bridge"
